import Vapor
import FBModels
import FBProviders

func routes(_ app: Application) throws {
    app.get { _ in
        "FlightBag API"
    }

    let v1 = app.grouped("v1")

    // Offline-download manifest, generated by `build-manifest` from the
    // artifact tree. Absent (fresh checkout, no artifacts yet) we serve an
    // empty manifest rather than 404 so clients degrade gracefully.
    v1.get("manifest") { req async throws -> DownloadManifest in
        let path = req.application.directory.publicDirectory + "artifacts/manifest.json"
        if let data = FileManager.default.contents(atPath: path) {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            return try decoder.decode(DownloadManifest.self, from: data)
        }
        return DownloadManifest(
            generatedAt: Date(),
            cycle: DataCycle.current().id,
            regions: [],
            products: []
        )
    }

    // Normalized METAR/TAF for one airport. The backend is a cache/etiquette
    // layer over aviationweather.gov (a per-station TTL cache keeps repeated
    // client requests from fanning out to the upstream API); the app also
    // keeps a direct path for in-flight fallback.
    v1.get("airports", ":id", "weather") { req async throws -> AirportWeatherResponse in
        guard let id = req.parameters.get("id") else {
            throw Abort(.badRequest)
        }
        let cache = req.application.weatherCache
        let key = id.uppercased()
        if let cached = await cache.cached(key) {
            return cached
        }
        let station = ICAOIdentifier(id)
        let provider = AviationWeatherGovProvider()
        async let metar = provider.metar(for: station)
        async let taf = provider.taf(for: station)
        let response = AirportWeatherResponse(station: station, metar: try await metar, taf: try await taf)
        await cache.store(key, response)
        return response
    }

    // NOTAMs for one airport. Unlike weather, this endpoint is the *only*
    // path the app has: the FAA's NOTAM Management Service authenticates with
    // OAuth client credentials that must not ship in an app binary, so the
    // token lives here and the app never talks to the FAA directly.
    v1.get("airports", ":id", "notams") { req async throws -> AirportNotamsResponse in
        guard let id = req.parameters.get("id") else {
            throw Abort(.badRequest)
        }
        let station = ICAOIdentifier(id)

        // No credentials configured is a normal state for a self-hoster, not
        // an error. Say so explicitly rather than returning an empty list the
        // app would render as "no NOTAMs here" — the dangerous reading.
        guard let provider = req.application.notamProvider else {
            return AirportNotamsResponse(station: station, configured: false, notams: [])
        }

        let cache = req.application.notamCache
        let key = id.uppercased()
        if let cached = await cache.cached(key) {
            return cached
        }
        do {
            let notams = try await provider.notams(for: station)
            let response = AirportNotamsResponse(station: station, configured: true, notams: notams)
            await cache.store(key, response)
            return response
        } catch {
            // 502, never an empty 200: the app must fall back to its own
            // cached NOTAMs rather than draw the conclusion that this airport
            // has none. Bad credentials and an FAA outage look the same from
            // here, so the detail goes to the log, not the client.
            req.logger.error("NMS NOTAM fetch failed for \(key): \(error)")
            throw Abort(.badGateway, reason: "NOTAM service unavailable")
        }
    }
}

struct AirportWeatherResponse: Content, Sendable {
    let station: ICAOIdentifier
    let metar: Metar?
    let taf: Taf?
}

struct AirportNotamsResponse: Content, Sendable {
    let station: ICAOIdentifier
    /// False when the server has no FAA NMS credentials. Lets the app tell
    /// "this server can't fetch NOTAMs" apart from "this airport has none".
    let configured: Bool
    let notams: [Notam]
}

/// Per-station TTL cache for the weather proxy: METAR/TAF refresh hourly, so a
/// short window collapses bursts of client requests into one upstream fetch
/// (the "etiquette" the endpoint promises aviationweather.gov).
actor WeatherCache {
    private struct Entry {
        let response: AirportWeatherResponse
        let fetchedAt: Date
    }

    private var entries: [String: Entry] = [:]
    private let ttl: TimeInterval

    init(ttl: TimeInterval = 300) {
        self.ttl = ttl
    }

    func cached(_ station: String, now: Date = Date()) -> AirportWeatherResponse? {
        guard let entry = entries[station], now.timeIntervalSince(entry.fetchedAt) < ttl else { return nil }
        return entry.response
    }

    func store(_ station: String, _ response: AirportWeatherResponse, now: Date = Date()) {
        entries[station] = Entry(response: response, fetchedAt: now)
    }
}

/// Per-station TTL cache for the NOTAM proxy. The TTL is far longer than the
/// weather one: NOTAMs change on the order of hours, the upstream is a
/// credentialed government API worth being frugal with, and a stale-by-minutes
/// NOTAM is not a safety difference — the app stamps everything with its age
/// regardless.
actor NotamCache {
    private struct Entry {
        let response: AirportNotamsResponse
        let fetchedAt: Date
    }

    private var entries: [String: Entry] = [:]
    private let ttl: TimeInterval

    init(ttl: TimeInterval = 900) {
        self.ttl = ttl
    }

    func cached(_ station: String, now: Date = Date()) -> AirportNotamsResponse? {
        guard let entry = entries[station], now.timeIntervalSince(entry.fetchedAt) < ttl else { return nil }
        return entry.response
    }

    func store(_ station: String, _ response: AirportNotamsResponse, now: Date = Date()) {
        entries[station] = Entry(response: response, fetchedAt: now)
    }
}

extension Application {
    private struct WeatherCacheKey: StorageKey {
        typealias Value = WeatherCache
    }

    private struct NotamCacheKey: StorageKey {
        typealias Value = NotamCache
    }

    private struct NotamProviderKey: StorageKey {
        typealias Value = FAANotamProvider
    }

    /// Configured once in `configure(_:)`; shared across requests.
    var weatherCache: WeatherCache {
        get {
            guard let cache = storage[WeatherCacheKey.self] else {
                fatalError("WeatherCache not configured — set app.weatherCache in configure(_:)")
            }
            return cache
        }
        set { storage[WeatherCacheKey.self] = newValue }
    }

    var notamCache: NotamCache {
        get {
            guard let cache = storage[NotamCacheKey.self] else {
                fatalError("NotamCache not configured — set app.notamCache in configure(_:)")
            }
            return cache
        }
        set { storage[NotamCacheKey.self] = newValue }
    }

    /// nil when no FAA NMS credentials are configured — a supported state,
    /// not a misconfiguration. One provider is shared so its OAuth token is
    /// fetched once rather than per request.
    var notamProvider: FAANotamProvider? {
        get { storage[NotamProviderKey.self] }
        set { storage[NotamProviderKey.self] = newValue }
    }
}

extension DownloadManifest: @retroactive RequestDecodable, @retroactive ResponseEncodable, @retroactive AsyncRequestDecodable, @retroactive AsyncResponseEncodable, Content {}
