import Vapor
import FBModels
import FBProviders

func routes(_ app: Application) throws {
    app.get { _ in
        "FlightBag API"
    }

    let v1 = app.grouped("v1")

    // Offline-download manifest, generated by `build-manifest` from the
    // artifact tree. Absent (fresh checkout, no artifacts yet) we serve an
    // empty manifest rather than 404 so clients degrade gracefully.
    v1.get("manifest") { req async throws -> DownloadManifest in
        let path = req.application.directory.publicDirectory + "artifacts/manifest.json"
        if let data = FileManager.default.contents(atPath: path) {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .iso8601
            return try decoder.decode(DownloadManifest.self, from: data)
        }
        return DownloadManifest(
            generatedAt: Date(),
            cycle: DataCycle.current().id,
            regions: [],
            products: []
        )
    }

    // Normalized METAR/TAF for one airport. The backend is a cache/etiquette
    // layer over aviationweather.gov; the app also keeps a direct path for
    // in-flight fallback.
    v1.get("airports", ":id", "weather") { req async throws -> AirportWeatherResponse in
        guard let id = req.parameters.get("id") else {
            throw Abort(.badRequest)
        }
        let station = ICAOIdentifier(id)
        let provider = AviationWeatherGovProvider()
        async let metar = provider.metar(for: station)
        async let taf = provider.taf(for: station)
        return AirportWeatherResponse(station: station, metar: try await metar, taf: try await taf)
    }
}

struct AirportWeatherResponse: Content {
    let station: ICAOIdentifier
    let metar: Metar?
    let taf: Taf?
}

extension DownloadManifest: @retroactive RequestDecodable, @retroactive ResponseEncodable, @retroactive AsyncRequestDecodable, @retroactive AsyncResponseEncodable, Content {}
